language: java
dist: trusty
addons:
  sonarcloud:
    organization: "test-web-app-performance-tool" # the key of the org you chose at step #3
    token:
      secure: 5e47d9af7974e84b3dfc101568b7d5cf2b2da217
script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar